// 周辺施設の簡易マップ用データ
export const surroundingFacilities = [
  {
    id: 1,
    name: 'たいらや 川鶴店',
    description:
      '徒歩約5分（450m）の距離にあるスーパー。団地内の主要スーパーで日用品から生鮮食品まで揃います。',
    distance: '徒歩約5分',
    category: 'ショッピング',
    icon: '🛒',
  },
  {
    id: 2,
    name: 'ファミリーマート かわつる三芳野店',
    description:
      '徒歩約4分（270m）の距離にある24時間営業のコンビニ。団地西側けやき通り沿いにあります。',
    distance: '徒歩約4分',
    category: 'ショッピング',
    icon: '🏪',
  },
  {
    id: 3,
    name: '川越川鶴郵便局',
    description:
      '徒歩約2分（140m）の距離にある郵便局。団地内に所在し、郵便物の送受信やATM利用ができます。',
    distance: '徒歩約2分',
    category: '公共施設',
    icon: '📮',
  },
  {
    id: 4,
    name: 'イーネットATM（ファミマ内）',
    description:
      '徒歩約4分（270m）の距離。ファミリーマート かわつる三芳野店内に設置されています。',
    distance: '徒歩約4分',
    category: '金融',
    icon: '🏦',
  },
  {
    id: 5,
    name: '川鶴プラザクリニック',
    description:
      '徒歩約0分、かわつる商店街にあるクリニック。内科などの診療を行っています。',
    distance: '徒歩約0分',
    category: '内科',
    icon: '🏥',
  },
  {
    id: 6,
    name: '川越市立川越西小学校',
    description:
      '徒歩約10分（約750m）の距離にある公立小学校。通学路も安全で安心です。',
    distance: '徒歩約10分',
    category: '教育',
    icon: '🏫',
  },
  {
    id: 7,
    name: '鶴ヶ島市運動公園',
    description:
      '車約2分（700m）の距離にある公園。鶴ヶ島市側に位置し、子供たちの遊び場として人気です。',
    distance: '車約2分',
    category: 'レジャー',
    icon: '🌳',
  },
  {
    id: 8,
    name: 'JR川越線 笠幡駅',
    description:
      '徒歩約24分（1.7km）の距離にある最寄り駅。都心へのアクセスにも便利です。',
    distance: '徒歩約24分',
    category: '交通',
    icon: '🚃',
  },
];

// 周辺の施設・お店データ（詳細版）
export const nearbyFacilities = {
  shoppingStreet: {
    id: 1,
    name: 'かわつる商店街',
    description:
      '団地に隣接する商店街。ベーカリー、カフェ、ドラッグストアなど、日々の買い物に便利な店舗が集まっています。',
    distance: '',
    category: '商店街',
    icon: '🏪',
    features: ['商店街', '複数店舗', '日々の買い物に便利', '駐車場完備'],
    hours: '',
    phone: '',
    website: 'https://www.instagram.com/kawatsuru.shoutengai/',
  },
  shopping: [
    {
      id: 1,
      name: 'ウェルパーク川越かわつる店',
      description:
        '団地に隣接するかわつる商店街にあるドラッグストア。日用品から医薬品まで揃います。',
      distance: '',
      category: 'ドラッグストア',
      icon: '💊',
      features: ['ドラッグストア', 'かわつる商店街', '駐車場完備'],
      hours: '',
      phone: '',
    },
    {
      id: 3,
      name: 'たいらや 川鶴店',
      description:
        '徒歩約5分（450m）の距離にあるスーパー。団地に近い主要スーパーで日用品から生鮮食品まで揃っています。',
      distance: '徒歩約5分',
      category: 'スーパー',
      icon: '🛒',
      features: ['生鮮食品', '日用品', '団地内主要スーパー'],
      hours: '',
      phone: '',
    },
    {
      id: 4,
      name: 'ファミリーマート かわつる三芳野店',
      description:
        '徒歩約4分（270m）の距離にある24時間営業のコンビニ。団地西側けやき通り沿いにあります。',
      distance: '徒歩約4分',
      category: 'コンビニ',
      icon: '🏪',
      features: ['24時間営業', 'ATM', 'コピー機', '宅配受取'],
      hours: '',
      phone: '',
    },
    {
      id: 5,
      name: 'セブンイレブン 鶴ヶ島運動公園前店',
      description:
        '徒歩約9分（約700m）の距離にあるコンビニ。鶴ヶ島市側に位置します。',
      distance: '徒歩約9分',
      category: 'コンビニ',
      icon: '🏪',
      features: ['24時間営業', 'ATM', 'コピー機', '鶴ヶ島市側'],
      hours: '',
      phone: '',
    },
    {
      id: 6,
      name: 'ベイシア 鶴ヶ島店',
      description: '車約3分（1.8km）の距離にある大型スーパー。',
      distance: '車約3分',
      category: 'スーパー',
      icon: '🛒',
      features: ['大型スーパー', '駐車場完備'],
      hours: '',
      phone: '',
    },
    {
      id: 7,
      name: 'カインズ 鶴ヶ島店',
      description:
        '車約4分（1.6km）の距離にあるホームセンター。日曜大工やガーデニング用品が充実しています。',
      distance: '車約4分',
      category: 'ホームセンター',
      icon: '🔨',
      features: [
        '日曜大工用品',
        'ガーデニング',
        'インテリア',
        'フードコート',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
    },
    {
      id: 8,
      name: 'カントリーファーム',
      description:
        'かわつる商店街にある八百屋。薬膳カレーなどの食事も提供しており、新鮮な野菜と温かい食事が楽しめます。',
      distance: '',
      category: '八百屋・レストラン',
      icon: '🥬',
      features: [
        '八百屋',
        '薬膳カレー',
        '食事提供',
        '新鮮な野菜',
        'かわつる商店街',
      ],
      hours: '',
      phone: '',
      website: 'https://www.facebook.com/Countryfarm39/',
    },
    {
      id: 9,
      name: 'ベーカリー・パンプキン',
      description:
        'かわつる商店街にあるベーカリー。手作りのパンやお菓子が楽しめます。',
      distance: '',
      category: 'ベーカリー',
      icon: '🍞',
      features: ['手作りパン', 'お菓子', 'テイクアウト', 'かわつる商店街'],
      hours: '',
      phone: '',
      website: 'https://www.instagram.com/bakery_pumpkin_kawatsuru/',
    },
    {
      id: 10,
      name: '川越総合地方卸売市場',
      description:
        '車約12分（5.2km）の距離にある市場。新鮮な野菜や魚介類が揃います。毎週土曜日は「お客様感謝市」として一般の方も利用できる市場開放日（8時からお昼頃まで開催）で、野菜・果物・お魚・お肉・総合食品など、豊富な品数と新鮮な食材を取り揃えています。',
      distance: '車約12分',
      category: '卸売市場',
      icon: '🏪',
      features: [
        '卸売市場',
        '新鮮な食材',
        'お客様感謝市（毎週土曜）',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://kawashijyo.xsrv.jp/shijyo/',
    },
    {
      id: 11,
      name: 'サイボク',
      description:
        '「牧場から食卓まで、まっすぐに」をコンセプトに、ブランド豚「ゴールデンポーク」や「スーパーゴールデンポーク」、保存料不使用のハム・ソーセージなど、安心・安全・新鮮にこだわった商品を取り揃えています。',
      distance: '車で約10分（4.8km）',
      category: '食肉・加工食品',
      icon: '🥓',
      features: [
        'ブランド豚',
        'ゴールデンポーク',
        'ハム・ソーセージ',
        '保存料不使用',
        'オンラインショップ',
      ],
      hours: '',
      phone: '',
      website: 'https://www.saiboku.co.jp/',
    },
    {
      id: 12,
      name: 'ワカバウォーク',
      description:
        '車約7分（約3.5km）の距離にある大型ショッピングモール。映画館「ユナイテッド・シネマわかば」をはじめ、ファッション、雑貨、レストランなど様々な店舗が集まっています。',
      distance: '車約7分',
      category: 'ショッピングモール',
      icon: '🛍️',
      features: [
        '大型ショッピングモール',
        '映画館',
        'ユナイテッド・シネマわかば',
        'ファッション',
        '雑貨',
        'レストラン',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://www.wakaba-walk.com/',
    },
    {
      id: 13,
      name: 'ロマン理容室',
      description:
        'かわつる商店街にある理容室。カットやシェービング、パーマなどのサービスを提供しています。',
      distance: '',
      category: '理容室',
      icon: '💇',
      features: [
        '理容室',
        'カット',
        'シェービング',
        'パーマ',
        'かわつる商店街',
      ],
      hours: '',
      phone: '',
      website: 'https://roman-net.co.jp/',
    },
    {
      id: 14,
      name: 'ヘアーブティックボーグ',
      description:
        'かわつる商店街にある美容院。カット、カラー、パーマなどのヘアサービスを提供しています。',
      distance: '',
      category: '美容院',
      icon: '💇‍♀️',
      features: ['美容院', 'カット', 'カラー', 'パーマ', 'かわつる商店街'],
      hours: '',
      phone: '',
      website: '',
    },
  ],
  restaurants: [],
  lifeServices: [
    {
      id: 1,
      name: '川越川鶴郵便局',
      description:
        '徒歩約2分（140m）の距離にある郵便局。団地内に所在し、郵便物の送受信やATM利用ができます。',
      distance: '徒歩約2分',
      category: '郵便局',
      icon: '📮',
      features: ['郵便サービス', 'ATM', '宅配受取', '保険サービス', '団地内'],
      hours: '',
      phone: '',
    },
    {
      id: 2,
      name: 'イーネットATM（ファミマ内）',
      description:
        '徒歩約4分（270m）の距離。ファミリーマート かわつる三芳野店内に設置されています。',
      distance: '徒歩約4分',
      category: 'ATM',
      icon: '🏦',
      features: ['24時間利用可能', 'イーネットATM'],
      hours: '',
      phone: '',
    },
    {
      id: 3,
      name: '武蔵野銀行 ATM（ザ・マーケットプレイス川越的場出張所）',
      description: '車約6分（約2.8km）の距離にあるATM。',
      distance: '車約6分',
      category: 'ATM',
      icon: '🏦',
      features: ['武蔵野銀行ATM', '駐車場完備'],
      hours: '',
      phone: '',
    },
    {
      id: 4,
      name: '川越市川鶴市民センター',
      description:
        '団地に隣接する市民センター。各種行政手続きや相談サービスを利用できます。住民異動、印鑑登録、戸籍関係、国民年金、国民健康保険などの手続きが可能です。',
      distance: '',
      category: '市民センター',
      icon: '🏛️',
      features: [
        '行政手続き',
        '相談サービス',
        '各種サービス',
        '団地に隣接',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website:
        'https://www.city.kawagoe.saitama.jp/shisei/shisetsu/gyosei/1013170/1013180.html',
    },
  ],
  medical: [
    {
      id: 1,
      name: '川鶴プラザクリニック',
      description:
        'かわつる商店街にあるクリニック。内科などの診療を行っています。',
      distance: '徒歩約0分（約20m）',
      category: 'クリニック',
      icon: '🏥',
      features: ['内科', 'かわつる商店街'],
      hours: '',
      phone: '',
      website: 'https://www.kawatsuru-plaza-clinic.jp/',
    },
    {
      id: 7,
      name: 'かわつる歯科医院',
      description:
        'かわつる商店街にある歯科医院。地域に根ざした歯科診療を提供しています。',
      distance: '徒歩約2分（約130m）',
      category: '歯科医院',
      icon: '🦷',
      features: ['歯科診療', 'かわつる商店街', '地域医療'],
      hours: '',
      phone: '',
    },
    {
      id: 8,
      name: 'あおぞら歯科クリニック',
      description:
        '患者様の気持ちを大切にした診療を心がける歯科クリニック。一般歯科、歯科口腔外科、小児歯科、歯周病、予防・メンテナンス、ホワイトニング、インプラント、矯正歯科、訪問診療など幅広い診療を行っています。',
      distance: '徒歩約5分（約350m）',
      category: '歯科クリニック',
      icon: '🦷',
      features: [
        '一般歯科',
        '小児歯科',
        '歯周病',
        'インプラント',
        '矯正歯科',
        'ホワイトニング',
        '訪問診療',
      ],
      hours: '',
      phone: '',
      website: 'https://www.aozoradental.jp/',
    },
    {
      id: 2,
      name: '埼玉医科大学総合医療センター',
      description:
        '車約10分の距離にある総合医療センター。大病院として24時間救急対応も可能です。',
      distance: '車約10分（約4.0km）',
      category: '総合病院',
      icon: '🏥',
      features: [
        '総合医療センター',
        '24時間救急対応',
        '各種診療科',
        '入院施設',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://www.kawagoe.saitama-med.ac.jp/',
    },
    {
      id: 3,
      name: 'オークスポーツクラブ鶴ヶ島',
      description: 'スポーツクラブ。運動を通じて健康づくりをサポートします。',
      distance: '車約3分（約1.3km）',
      category: 'スポーツクラブ',
      icon: '💪',
      features: ['スポーツクラブ', 'フィットネス', '健康づくり'],
      hours: '',
      phone: '',
    },
    {
      id: 4,
      name: 'コナミスポーツクラブ 川越',
      description:
        'スポーツクラブ。様々な運動プログラムで健康管理をサポートします。',
      distance: '車約3分（約1.5km）',
      category: 'スポーツクラブ',
      icon: '💪',
      features: ['スポーツクラブ', 'フィットネス', '健康管理'],
      hours: '',
      phone: '',
    },
    {
      id: 5,
      name: 'なぐわし公園ＰｉＫＯＡ',
      description:
        '隣接の資源化センターから発生する熱エネルギーを有効活用した最新のエコ温水プールをはじめ、お子さまから大人まで誰もが気軽にご利用いただける、運動施設や多目的ホールを設けてある。',
      distance: '車約8分（約4.8km）',
      category: '健康施設',
      icon: '🏃',
      features: [
        'エコ温水プール',
        '運動施設',
        '多目的ホール',
        'お子さまから大人まで',
      ],
      hours: '',
      phone: '',
      website: 'https://information.konamisportsclub.jp/trust/pikoa/',
    },
    {
      id: 9,
      name: 'かがやき整骨院',
      description:
        'かわつる商店街にある整骨院。腰痛、肩こり、スポーツ障害などの治療を行っています。',
      distance: '',
      category: '整骨院',
      icon: '💆',
      features: [
        '整骨院',
        '腰痛治療',
        '肩こり治療',
        'スポーツ障害',
        'かわつる商店街',
      ],
      hours: '',
      phone: '',
      website: 'https://i-jam2004.com/information/',
    },
  ],
  education: [
    {
      id: 1,
      name: '川越市立川越西小学校',
      description:
        '徒歩約10分（約750m）の距離にある公立小学校。通学路は歩道が完備されているため安全で安心です。',
      distance: '徒歩約10分',
      category: '公立小学校',
      icon: '🏫',
      features: [
        '公立小学校',
        '通学路の安全',
        '給食提供',
        'PTA活動',
        '地域連携',
      ],
      hours: '',
      phone: '',
    },
    {
      id: 2,
      name: '川越市立川越西中学校',
      description:
        '徒歩約12分（約900m）の距離で川越西小学校に隣接する公立中学校。充実した学習環境と部活動で、お子様の成長をサポートします。',
      distance: '徒歩約12分',
      category: '公立中学校',
      icon: '🎓',
      features: [
        '公立中学校',
        '充実した学習環境',
        '部活動',
        '進路指導',
        '給食提供',
        'PTA活動',
      ],
      hours: '',
      phone: '',
    },
    {
      id: 3,
      name: '川鶴ひばり幼稚園',
      description: '団地に隣接する幼稚園です。',
      distance: '徒歩0分',
      category: '幼稚園',
      icon: '🎨',
      features: ['団地内', '川鶴3丁目10'],
      hours: '',
      phone: '',
      website: 'https://www.kawagoe-hibari.ed.jp/kawatsuru/',
    },
    {
      id: 4,
      name: '川越市立川鶴保育園',
      description:
        '団地に隣接する保育園です。0歳から5歳までのお子様をお預かりします。',
      distance: '徒歩0分',
      category: '保育園',
      icon: '👶',
      features: ['認可保育園', '延長保育', '給食提供', '専門スタッフ'],
      hours: '',
      phone: '',
    },
    {
      id: 5,
      name: '埼玉県立川越西高等学校',
      description:
        '約2.3kmの距離にある県立高等学校。全日制普通科の学校で、充実した学習環境と部活動が特徴です。',
      distance: '自転車約10分、徒歩約30分',
      category: '県立高等学校',
      icon: '🎓',
      features: [
        '県立高等学校',
        '全日制普通科',
        '充実した学習環境',
        '部活動',
        '進路指導',
      ],
      hours: '',
      phone: '',
      website: 'https://kawagoenishi-h.spec.ed.jp/',
    },
    {
      id: 6,
      name: '東洋大学理工学部川越キャンパス',
      description:
        '「工」と「理」の知を融合し、次世代のものづくりへ。自然やいのちとの調和あるテクノロジーを創出することを掲げる理工学部。機械工学科、電気電子情報工学科、応用化学科、都市環境デザイン学科、建築学科が設置されています。',
      distance: '車約4分（約2.7km）',
      category: '私立大学',
      icon: '🏛️',
      features: ['私立大学', '理工学部', '5学科', '自然との調和', 'ものづくり'],
      hours: '',
      phone: '',
      website: 'https://www.toyo.ac.jp/academics/sce/',
    },
  ],
  publicTransport: [
    {
      id: 1,
      name: 'JR川越線 笠幡駅',
      description:
        '徒歩約24分（1.7km）の距離にある最寄り駅。都心へのアクセスにも便利です。',
      distance: '徒歩約24分',
      category: 'JR駅',
      icon: '🚃',
      features: ['JR川越線', '都心直通'],
      hours: '',
      phone: '',
      website:
        'https://www.jreast.co.jp/estation/station/info.aspx?StationCd=426',
    },
    {
      id: 2,
      name: '東武東上線 鶴ヶ島駅',
      description:
        '車で約7分（2.6km）の距離にある駅。都心へのアクセスに便利です。',
      distance: '車で約7分',
      category: '東武駅',
      icon: '🚃',
      features: ['東武東上線', '都心直通', '駐車場完備'],
      hours: '',
      phone: '',
      website: 'https://www.tobu.co.jp/railway/guide/station/info/7402.html',
    },
    {
      id: 3,
      name: '東武バス 川鶴団地',
      description:
        '団地内にあるバス停。最寄り駅や周辺地域へのアクセスに便利です。',
      distance: '徒歩0分',
      category: 'バス停',
      icon: '🚌',
      features: ['団地内', '最寄り駅アクセス'],
      hours: '',
      phone: '',
      website:
        'https://transfer-cloud.navitime.biz/tobubus/courses?busstop=00311025',
    },
    {
      id: 4,
      name: '東武バス 川鶴センター',
      description:
        '団地内の川鶴センター付近にあるバス停。商店街やクリニックへのアクセスにも便利です。',
      distance: '徒歩約1分',
      category: 'バス停',
      icon: '🚌',
      features: ['川鶴センター付近', '商店街アクセス', 'クリニックアクセス'],
      hours: '',
      phone: '',
      website:
        'https://transfer-cloud.navitime.biz/tobubus/courses?busstop=00311024',
    },
    {
      id: 5,
      name: '東武バス 川鶴三芳野',
      description:
        '団地周辺にあるバス停。かわつる三芳野団地へのアクセスに便利です。',
      distance: '徒歩約2分',
      category: 'バス停',
      icon: '🚌',
      features: ['団地周辺', '三芳野団地アクセス'],
      hours: '',
      phone: '',
      website:
        'https://transfer-cloud.navitime.biz/tobubus/courses?busstop=00311060',
    },
  ],
  leisure: [
    {
      id: 1,
      name: '笠幡公園',
      description:
        '団地に隣接する公園。野球グラウンドや遊具があり、樹木に囲まれた自然な雰囲気で散歩に最適です。',
      distance: '徒歩0分',
      category: '公園',
      icon: '🌳',
      features: ['公園', '遊具', '野球グラウンド', '駐車場完備'],
      hours: '',
      phone: '',
      website:
        'https://www.city.kawagoe.saitama.jp/kurashi/sports/1003258/1003275/1003285.html',
    },
    {
      id: 2,
      name: '鶴ヶ島南近隣公園',
      description:
        '300mの距離にある公園。鶴ヶ島市側に位置します。野球グラウンドや遊具があり、樹木に囲まれた自然な雰囲気で散歩に最適です。',
      distance: '徒歩約5分',
      category: '公園',
      icon: '🌳',
      features: ['近隣公園', '遊具', '野球グラウンド', '駐車場完備'],
      hours: '',
      phone: '',
      website:
        'https://www.city.tsurugashima.lg.jp/kurashi-tetsuduki/kouen-ryokuchi/other/page002665.html',
    },
    {
      id: 3,
      name: '鶴ヶ島市運動公園',
      description:
        '既存樹木を最大限に活用した樹林地、太田ヶ谷沼を中心とした水辺、メイングラウンドを中心とした運動施設などがあります。',
      distance: '車約2分、徒歩約10分',
      category: '公園',
      icon: '🌳',
      features: ['運動公園', '遊具', '鶴ヶ島市側', '駐車場完備'],
      hours: '',
      phone: '',
      website:
        'https://www.city.tsurugashima.lg.jp/kurashi-tetsuduki/kouen-ryokuchi/page000474.html',
    },
    {
      id: 4,
      name: '御伊勢塚公園',
      description:
        '車で約3分（1.7km）の距離にある公園。武蔵野の面影の代表である雑木林をそのまま残した森やカッパをイメージした楽しいモニュメント、ひょうたん型をした池、いろいろな用途に使える芝生広場等があります。',
      distance: '車で約3分（1.7km）',
      category: '公園',
      icon: '🌳',
      features: [
        '雑木林',
        '芝生広場',
        'フィールドアスレチック',
        'テニスコート',
        'ゲートボール場',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website:
        'https://www.city.kawagoe.saitama.jp/kurashi/sports/1003258/1003275/1003283.html',
    },
    {
      id: 5,
      name: '川越水上公園',
      description:
        '車約12分（5.7km）の距離にある水上公園。公益財団法人埼玉県公園緑地協会が管理しています。4種類のスライダープール、造波プール、飛び込み可能なプールなど、種類豊富なプール施設が楽しめます。',
      distance: '車約12分',
      category: '水上公園',
      icon: '🏊',
      features: [
        '水上公園',
        'スライダープール（4種類）',
        '造波プール',
        '飛び込みプール',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://www.parks.or.jp/kawagoesuijo/',
    },
  ],
  tourism: [
    {
      id: 1,
      name: '小江戸川越の蔵造りの町並み',
      description:
        '車約15分（約8km）の距離にある川越の代表的な観光スポット。江戸時代から続く蔵造りの建物が並ぶ歴史ある町並みで、甘味処や雑貨店などが軒を連ねています。重要伝統的建造物群保存地区に指定されており、タイムスリップしたような雰囲気を味わえます。',
      distance: '車約15分',
      category: '観光地・歴史',
      icon: '🏯',
      features: [
        '蔵造りの町並み',
        '重要伝統的建造物群保存地区',
        '甘味処',
        '雑貨店',
        '歴史的建造物',
        '観光スポット',
      ],
      hours: '',
      phone: '',
      website: 'https://koedo.or.jp/',
    },
    {
      id: 2,
      name: '巾着田',
      description:
        '車約20分（約12km）の距離にある名所。毎年9月下旬から10月上旬にかけて500万本の曼珠沙華（ヒガンバナ）が咲き誇ることで知られています。秋には曼珠沙華の鮮やかな赤色が一面に広がり、多くの観光客が訪れる人気のスポットです。',
      distance: '車約20分',
      category: '観光地・自然',
      icon: '🌺',
      features: [
        '曼珠沙華の名所',
        '500万本のヒガンバナ',
        '秋の観光スポット',
        '自然',
        '散策コース',
        'BBQ・バーベキュー',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://kinchakuda.com/',
    },
    {
      id: 3,
      name: 'ムーミンバレーパーク',
      description:
        '車約30分（約20km）の距離にあるテーマパーク。フィンランドの童話作家トーベ・ヤンソンが生み出したムーミンの世界を体感できるアミューズメントパークです。ムーミン屋敷やアトラクション、ショップなど、家族で楽しめる施設が充実しています。',
      distance: '車約30分',
      category: 'テーマパーク',
      icon: '🎠',
      features: [
        'テーマパーク',
        'ムーミンの世界',
        'アトラクション',
        'ショップ',
        '家族で楽しめる',
        '駐車場完備',
      ],
      hours: '',
      phone: '',
      website: 'https://metsa-hanno.com/',
    },
  ],
};
