// 周辺施設データ（新カテゴリ構造）
export const nearbyFacilities = {
  // 公共施設(nearby_public)
  publicFacilities: [
    {
      id: 1,
      name: '川越川鶴郵便局',
      description: '徒歩約2分（140m）',
      subCategory: 'publicFacilities',
      category: 'neighborhood',
      icon: '📮',
      order: 1,
    },
    {
      id: 2,
      name: '川越市川鶴市民センター',
      description: '徒歩約2分（140m）',
      subCategory: 'publicFacilities',
      category: 'neighborhood',
      icon: '🏛️',
      order: 2,
    },
  ],

  // 教育施設(nearby_education)
  educationFacilities: [
    {
      id: 1,
      name: '川越市立川越西小学校',
      description: '徒歩約10分（約750m）',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '🏫',
      order: 1,
    },
    {
      id: 2,
      name: '川越市立川越西中学校',
      description: '徒歩約12分（約900m）',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '🎓',
      order: 2,
    },
    {
      id: 3,
      name: '川鶴ひばり幼稚園',
      description: '団地に隣接',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '🎨',
      order: 3,
    },
    {
      id: 4,
      name: '川越市立川鶴保育園',
      description: '団地に隣接',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '👶',
      order: 4,
    },
    {
      id: 5,
      name: '埼玉県立川越西高等学校',
      description: '自転車約10分、徒歩約30分（約2.3km）',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '🎓',
      order: 5,
    },
    {
      id: 6,
      name: '東洋大学理工学部川越キャンパス',
      description: '車約4分（約2.7km）',
      subCategory: 'educationFacilities',
      category: 'neighborhood',
      icon: '🏛️',
      order: 6,
    },
  ],

  // 金融機関(nearby_finance)
  financialInstitutions: [
    {
      id: 1,
      name: 'イーネットATM（ファミマ内）',
      description: '徒歩約4分（270m）',
      subCategory: 'financialInstitutions',
      category: 'neighborhood',
      icon: '🏦',
      order: 1,
    },
    {
      id: 2,
      name: '武蔵野銀行 ATM（ザ・マーケットプレイス川越的場出張所）',
      description: '車約6分（約2.8km）',
      subCategory: 'financialInstitutions',
      category: 'neighborhood',
      icon: '🏦',
      order: 2,
    },
  ],

  // 商業施設(nearby_commerce)
  commercialFacilities: [
    {
      id: 1,
      name: 'かわつる商店街',
      description: '団地に隣接',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🏪',
      order: 1,
    },
    {
      id: 2,
      name: 'ウェルパーク川越かわつる店',
      description: 'かわつる商店街内',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '💊',
      order: 2,
    },
    {
      id: 3,
      name: 'たいらや 川鶴店',
      description: '徒歩約5分（450m）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🛒',
      order: 3,
    },
    {
      id: 4,
      name: 'ファミリーマート かわつる三芳野店',
      description: '徒歩約4分（270m）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🏪',
      order: 4,
    },
    {
      id: 5,
      name: 'セブンイレブン 鶴ヶ島運動公園前店',
      description: '徒歩約9分（約700m）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🏪',
      order: 5,
    },
    {
      id: 6,
      name: 'ベイシア 鶴ヶ島店',
      description: '車約3分（1.8km）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🛒',
      order: 6,
    },
    {
      id: 7,
      name: 'カインズ 鶴ヶ島店',
      description: '車約4分（1.6km）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🔨',
      order: 7,
    },
    {
      id: 8,
      name: 'カントリーファーム',
      description: 'かわつる商店街内',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🥬',
      order: 8,
    },
    {
      id: 9,
      name: 'ベーカリー・パンプキン',
      description: 'かわつる商店街内',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🍞',
      order: 9,
    },
    {
      id: 10,
      name: '川越総合地方卸売市場',
      description: '車約12分（5.2km）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🏪',
      order: 10,
    },
    {
      id: 11,
      name: 'サイボク',
      description: '車で約10分（4.8km）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🥓',
      order: 11,
    },
    {
      id: 12,
      name: 'ワカバウォーク',
      description: '車約7分（約3.5km）',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '🛍️',
      order: 12,
    },
    {
      id: 13,
      name: 'ロマン理容室',
      description: 'かわつる商店街内',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '💇',
      order: 13,
    },
    {
      id: 14,
      name: 'ヘアーブティックボーグ',
      description: 'かわつる商店街内',
      subCategory: 'commercialFacilities',
      category: 'neighborhood',
      icon: '💇‍♀️',
      order: 14,
    },
  ],

  // 医療施設(nearby_medical)
  medicalFacilities: [
    {
      id: 1,
      name: '川鶴プラザクリニック',
      description: 'かわつる商店街内',
      subCategory: 'medicalFacilities',
      category: 'neighborhood',
      icon: '🏥',
      order: 1,
    },
    {
      id: 2,
      name: 'かわつる歯科医院',
      description: 'かわつる商店街内',
      subCategory: 'medicalFacilities',
      category: 'neighborhood',
      icon: '🦷',
      order: 2,
    },
    {
      id: 3,
      name: 'あおぞら歯科クリニック',
      description: '徒歩約5分（約350m）',
      subCategory: 'medicalFacilities',
      category: 'neighborhood',
      icon: '🦷',
      order: 3,
    },
    {
      id: 4,
      name: '埼玉医科大学総合医療センター',
      description: '車約10分（約4.0km）',
      subCategory: 'medicalFacilities',
      category: 'neighborhood',
      icon: '🏥',
      order: 4,
    },
    {
      id: 5,
      name: 'かがやき整骨院',
      description: 'かわつる商店街内',
      subCategory: 'medicalFacilities',
      category: 'neighborhood',
      icon: '💆',
      order: 5,
    },
  ],

  // その他（電気、ガス、水道、ごみ処理）(nearby_other)
  utilities: [],
};

// 周辺施設カテゴリ定義
export const surroundingCategories = [
  { id: 'publicFacilities', label: '公共施設', icon: '🏛️' },
  { id: 'educationFacilities', label: '教育施設', icon: '🏫' },
  { id: 'financialInstitutions', label: '金融機関', icon: '🏦' },
  { id: 'commercialFacilities', label: '商業施設', icon: '🛒' },
  { id: 'medicalFacilities', label: '医療施設', icon: '🏥' },
  { id: 'utilities', label: 'その他', icon: '⚡' },
];
